In [139]:
# Importa bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [140]:
# Leitura do CSV cercado por um tratador de exceções
try:
    votos_por_municipio_df = pd.read_csv('votacao_candidato-municipio_presidente_2022.csv', sep=';', encoding='iso-8859-1')
    print('CSV lido com sucesso')
except FileNotFoundError:
    print('Arquivo não encontrado')

CSV lido com sucesso

In [141]:
votos_por_municipio_df.head()

,sg_uf,nm_municipio,cd_cargo,ds_cargo,nr_candidato,nm_candidato,nm_urna_candidato,sg_partido,ds_composicao_coligacao,nr_turno,ds_sit_totalizacao,nm_tipo_destinacao_votos,dt_ult_totalizacao,pc_votos_validos,qt_votos_nom_validos,qt_votos_concorrentes
0,AC,ACRELÂNDIA,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,1,Segundo turno,Válido,2022-10-04 12:06:36,"0,7359",5238,7118
1,AC,ACRELÂNDIA,1,Presidente,13,LUIZ INÁCIO LULA DA SILVA,LULA,PT,Federação Brasil da Esperança - FE BRASIL(PT/P...,1,Segundo turno,Válido,2022-10-04 12:06:36,"0,213",1516,7118
2,AC,ACRELÂNDIA,1,Presidente,15,SIMONE NASSAR TEBET,SIMONE TEBET,MDB,MDB / Federação PSDB Cidadania(PSDB/CIDADANIA)...,1,Não Eleito,Válido,2022-10-04 12:06:36,"0,027",192,7118
3,AC,ACRELÂNDIA,1,Presidente,12,CIRO FERREIRA GOMES,CIRO GOMES,PDT,PDT,1,Não Eleito,Válido,2022-10-04 12:06:36,"0,0164",117,7118
4,AC,ACRELÂNDIA,1,Presidente,44,SORAYA VIEIRA THRONICKE,SORAYA THRONICKE,UNIÃO,UNIÃO,1,Não Eleito,Válido,2022-10-04 12:06:36,"0,0052",37,7118

In [142]:
# votos_por_municipio_df.info()

In [143]:
votos_por_municipio_df['pc_votos_validos'] = votos_por_municipio_df['pc_votos_validos'].str.replace(',','.')
votos_por_municipio_df['pc_votos_validos'] = votos_por_municipio_df['pc_votos_validos'].astype(float)

In [144]:
votos_por_municipio_df['dt_ult_totalizacao'] = pd.to_datetime(votos_por_municipio_df['dt_ult_totalizacao'])

In [145]:
# votos_por_municipio_df.info()

In [146]:
votos_por_municipio_df.head()

,sg_uf,nm_municipio,cd_cargo,ds_cargo,nr_candidato,nm_candidato,nm_urna_candidato,sg_partido,ds_composicao_coligacao,nr_turno,ds_sit_totalizacao,nm_tipo_destinacao_votos,dt_ult_totalizacao,pc_votos_validos,qt_votos_nom_validos,qt_votos_concorrentes
0,AC,ACRELÂNDIA,1,Presidente,22,JAIR MESSIAS BOLSONARO,JAIR BOLSONARO,PL,PP / REPUBLICANOS / PL,1,Segundo turno,Válido,2022-10-04 12:06:36,0.7359,5238,7118
1,AC,ACRELÂNDIA,1,Presidente,13,LUIZ INÁCIO LULA DA SILVA,LULA,PT,Federação Brasil da Esperança - FE BRASIL(PT/P...,1,Segundo turno,Válido,2022-10-04 12:06:36,0.2130,1516,7118
2,AC,ACRELÂNDIA,1,Presidente,15,SIMONE NASSAR TEBET,SIMONE TEBET,MDB,MDB / Federação PSDB Cidadania(PSDB/CIDADANIA)...,1,Não Eleito,Válido,2022-10-04 12:06:36,0.0270,192,7118
3,AC,ACRELÂNDIA,1,Presidente,12,CIRO FERREIRA GOMES,CIRO GOMES,PDT,PDT,1,Não Eleito,Válido,2022-10-04 12:06:36,0.0164,117,7118
4,AC,ACRELÂNDIA,1,Presidente,44,SORAYA VIEIRA THRONICKE,SORAYA THRONICKE,UNIÃO,UNIÃO,1,Não Eleito,Válido,2022-10-04 12:06:36,0.0052,37,7118

In [147]:
# Leitura do CSV cercado por um tratador de exceções
try:
    votaçao_por_municipio_df = pd.read_csv('votacao_candidato.csv', sep= ';', encoding='iso-8859-1')
    print('CSV lido com sucesso')
except FileNotFoundError:
    print('Arquivo não encontrado')

CSV lido com sucesso

In [148]:
# Validação de Granularidade: Antes de realizar o merge, foi isolado o município de BUJARI para checar a presença de múltiplas 
# linhas por conta das zonas eleitorais e validar os tipos das chaves.

# teste = votaçao_por_municipio_df[votaçao_por_municipio_df['Município'] == 'BUJARI']
# teste.head()

In [149]:
# votaçao_por_municipio_df.info()

In [150]:
votaçao_por_municipio_df['Data de carga'] = pd.to_datetime(votaçao_por_municipio_df['Data de carga'])

In [151]:
# votaçao_por_municipio_df.info()

In [152]:
try:
    cod_municipio = pd.read_csv('municipio_tse_ibge.csv', sep= ';', encoding='iso-8859-1')
    print('CSV lido com sucesso')
except FileNotFoundError:
    print('Arquivo não encontrado')

CSV lido com sucesso

In [153]:
cod_municipio.head()

,DT_GERACAO,HH_GERACAO,CD_UF_TSE,CD_UF_IBGE,SG_UF,NM_UF,CD_MUNICIPIO_TSE,NM_MUNICIPIO_TSE,CD_MUNICIPIO_IBGE,NM_MUNICIPIO_IBGE
0,28/06/2026,09:00:07,24,12,AC,Acre,1007,Bujari,1200138,Bujari
1,28/06/2026,09:00:07,24,12,AC,Acre,1015,Capixaba,1200179,Capixaba
2,28/06/2026,09:00:07,24,12,AC,Acre,1023,Porto Acre,1200807,Porto Acre
3,28/06/2026,09:00:07,24,12,AC,Acre,1031,Santa Rosa Do Purus,1200435,Santa Rosa Do Purus
4,28/06/2026,09:00:07,24,12,AC,Acre,1040,Marechal Thaumaturgo,1200351,Marechal Thaumaturgo

In [154]:
# cod_municipio.info()

In [155]:
votacao_municipio_cod_df = votaçao_por_municipio_df.merge(cod_municipio, left_on= 'Código município', right_on='CD_MUNICIPIO_TSE')

In [156]:
votacao_municipio_cod_df.head()

,Ano de eleição,Cargo,Código município,Município,Nome candidato,Número candidato,Partido,Região,Situação totalização,Turno,...,DT_GERACAO,HH_GERACAO,CD_UF_TSE,CD_UF_IBGE,SG_UF,NM_UF,CD_MUNICIPIO_TSE,NM_MUNICIPIO_TSE,CD_MUNICIPIO_IBGE,NM_MUNICIPIO_IBGE
0,2022,Presidente,41238,BELO HORIZONTE,SIMONE NASSAR TEBET,15,MDB,SUDESTE,Não Eleito,1,...,28/06/2026,09:00:07,2,31,MG,Minas Gerais,41238,Belo Horizonte,3106200,Belo Horizonte
1,2022,Presidente,82830,RIO DAS ANTAS,SIMONE NASSAR TEBET,15,MDB,SUL,Não Eleito,1,...,28/06/2026,09:00:07,9,42,SC,Santa Catarina,82830,Rio Das Antas,4214409,Rio Das Antas
2,2022,Presidente,11959,SÃO GONÇALO DO PIAUÍ,SIMONE NASSAR TEBET,15,MDB,NORDESTE,Não Eleito,1,...,28/06/2026,09:00:07,15,22,PI,Piauí,11959,São Gonçalo Do Piauí,2209807,São Gonçalo Do Piauí
3,2022,Presidente,84921,BOQUEIRÃO DO LEÃO,SIMONE NASSAR TEBET,15,MDB,SUL,Não Eleito,1,...,28/06/2026,09:00:07,4,43,RS,Rio Grande Do Sul,84921,Boqueirão Do Leão,4302451,Boqueirão Do Leão
4,2022,Presidente,36552,JAGUARARI,SIMONE NASSAR TEBET,15,MDB,NORDESTE,Não Eleito,1,...,28/06/2026,09:00:07,5,29,BA,Bahia,36552,Jaguarari,2917706,Jaguarari

In [157]:
# votacao_municipio_cod_df.info()

In [158]:
vot_mun_cod_df_agrupado = votacao_municipio_cod_df.groupby(['CD_MUNICIPIO_IBGE','Município','UF', 'Turno', 'Nome candidato', 'Partido', 'Cargo']).agg({'Votos válidos' : 'sum', 'Votos nominais' : 'sum'}).reset_index().sort_values(by='Votos nominais', ascending=False)

In [159]:
vot_mun_cod_df_agrupado.head()

,CD_MUNICIPIO_IBGE,Município,UF,Turno,Nome candidato,Partido,Cargo,Votos válidos,Votos nominais
49789,3550308,SÃO PAULO,SP,2,LUIZ INÁCIO LULA DA SILVA,PT,Presidente,6869405,3677921
49783,3550308,SÃO PAULO,SP,1,LUIZ INÁCIO LULA DA SILVA,PT,Presidente,6892638,3276512
49788,3550308,SÃO PAULO,SP,2,JAIR MESSIAS BOLSONARO,PL,Presidente,6869405,3191484
49778,3550308,SÃO PAULO,SP,1,JAIR MESSIAS BOLSONARO,PL,Presidente,6892638,2618593
42157,3304557,RIO DE JANEIRO,RJ,2,JAIR MESSIAS BOLSONARO,PL,Presidente,3663368,1929209

In [160]:
vot_mun_cod_df_agrupado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 72410 entries, 49789 to 52580
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CD_MUNICIPIO_IBGE  72410 non-null  int64
 1   Município          72410 non-null  object
 2   UF                 72410 non-null  object
 3   Turno              72410 non-null  int64
 4   Nome candidato     72410 non-null  object
 5   Partido            72410 non-null  object
 6   Cargo              72410 non-null  object
 7   Votos válidos      72410 non-null  int64
 8   Votos nominais     72410 non-null  int64
dtypes: int64(4), object(5)
memory usage: 5.5+ MB

In [161]:
try:
    municipios_df = pd.read_csv('dim_municipio_socioeconomico.csv', sep= ',', encoding='iso-8859-1')
    print('CSV lido com sucesso')
except FileNotFoundError:
    print('Arquivo não encontrado')

CSV lido com sucesso

In [162]:
municipios_df.head()

,CD_MUNICIPIO_IBGE,ano,renda_pc,prop_ocupados_agropecuaria,prop_ocupados_comercio,prop_ocupados_construcao,prop_ocupados_servicos,prop_ocupados_transformacao,idhm,idhm_r
0,1100015,2010,476.99,38.56,13.78,5.31,33.18,3.26,0.641,0.657
1,1100023,2010,689.95,14.97,17.99,8.68,40.06,9.10,0.702,0.716
2,1100031,2010,457.17,45.49,6.46,3.62,36.91,3.98,0.650,0.650
3,1100049,2010,738.06,19.69,19.00,7.16,39.07,10.43,0.718,0.727
4,1100056,2010,577.18,26.67,14.08,8.60,38.39,6.87,0.692,0.688

In [165]:
df_fato_final = vot_mun_cod_df_agrupado.merge(municipios_df, on= 'CD_MUNICIPIO_IBGE', how= 'left').reset_index()

In [167]:
df_fato_final.head()

,index,CD_MUNICIPIO_IBGE,Município,UF,Turno,Nome candidato,Partido,Cargo,Votos válidos,Votos nominais,ano,renda_pc,prop_ocupados_agropecuaria,prop_ocupados_comercio,prop_ocupados_construcao,prop_ocupados_servicos,prop_ocupados_transformacao,idhm,idhm_r
0,0,3550308,SÃO PAULO,SP,2,LUIZ INÁCIO LULA DA SILVA,PT,Presidente,6869405,3677921,2010.0,1516.21,0.33,16.01,5.39,57.07,11.36,0.805,0.843
1,1,3550308,SÃO PAULO,SP,1,LUIZ INÁCIO LULA DA SILVA,PT,Presidente,6892638,3276512,2010.0,1516.21,0.33,16.01,5.39,57.07,11.36,0.805,0.843
2,2,3550308,SÃO PAULO,SP,2,JAIR MESSIAS BOLSONARO,PL,Presidente,6869405,3191484,2010.0,1516.21,0.33,16.01,5.39,57.07,11.36,0.805,0.843
3,3,3550308,SÃO PAULO,SP,1,JAIR MESSIAS BOLSONARO,PL,Presidente,6892638,2618593,2010.0,1516.21,0.33,16.01,5.39,57.07,11.36,0.805,0.843
4,4,3304557,RIO DE JANEIRO,RJ,2,JAIR MESSIAS BOLSONARO,PL,Presidente,3663368,1929209,2010.0,1492.63,0.31,16.44,5.91,61.93,6.32,0.799,0.840

In [169]:
df_fato_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72410 entries, 0 to 72409
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   index                        72410 non-null  int64
 1   CD_MUNICIPIO_IBGE            72410 non-null  int64
 2   Município                    72410 non-null  object
 3   UF                           72410 non-null  object
 4   Turno                        72410 non-null  int64
 5   Nome candidato               72410 non-null  object
 6   Partido                      72410 non-null  object
 7   Cargo                        72410 non-null  object
 8   Votos válidos                72410 non-null  int64
 9   Votos nominais               72410 non-null  int64
 10  ano                          72345 non-null  float64
 11  renda_pc                     72345 non-null  float64
 12  prop_ocupados_agropecuaria   72345 non-null  float64
 13  prop_ocupados_comercio       72345 non-null  float64
 14  prop_ocupados_construcao     72345 non-null  float64
 15  prop_ocupados_servicos       72345 non-null  float64
 16  prop_ocupados_transformacao  72345 non-null  float64
 17  idhm                         72345 non-null  float64
 18  idhm_r                       72345 non-null  float64
dtypes: float64(9), int64(5), object(5)
memory usage: 10.5+ MB

In [170]:
# Limpeza de nulos
df_fato_final = df_fato_final.dropna(subset=['idhm'])
df_fato_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 72345 entries, 0 to 72409
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   index                        72345 non-null  int64
 1   CD_MUNICIPIO_IBGE            72345 non-null  int64
 2   Município                    72345 non-null  object
 3   UF                           72345 non-null  object
 4   Turno                        72345 non-null  int64
 5   Nome candidato               72345 non-null  object
 6   Partido                      72345 non-null  object
 7   Cargo                        72345 non-null  object
 8   Votos válidos                72345 non-null  int64
 9   Votos nominais               72345 non-null  int64
 10  ano                          72345 non-null  float64
 11  renda_pc                     72345 non-null  float64
 12  prop_ocupados_agropecuaria   72345 non-null  float64
 13  prop_ocupados_comercio       72345 non-null  float64
 14  prop_ocupados_construcao     72345 non-null  float64
 15  prop_ocupados_servicos       72345 non-null  float64
 16  prop_ocupados_transformacao  72345 non-null  float64
 17  idhm                         72345 non-null  float64
 18  idhm_r                       72345 non-null  float64
dtypes: float64(9), int64(5), object(5)
memory usage: 11.0+ MB

In [173]:
df_fato_final.to_csv('fato_votacao_socioeconomica_2022.csv', sep=';', index=False, encoding='utf-8')
print("Tabela Fato gerada com sucesso! Exportada e pronta pro Power BI.")

Tabela Fato gerada com sucesso! Exportada e pronta pro Power BI.